runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:application

runtime_config:
  python_version: 2

handlers:
- url: /dist
  static_dir: dist

env_variables:
  ALINA_API_KEY: gRElaoboxxL05Jutyiyui2HMI57yMgnhcgZyuytutyuoBfkt2eWSI4v9I
